/**
 * OurGame API
 * 
 * Export all API client functionality from a single entry point.
 * 
 * Usage:
 * ```typescript
 * import { apiClient, useMyTeams } from '@/api';
 * ```
 */

// Client and types
export { apiClient, getApiBaseUrl } from './client';
export type {
  ApiResponse,
  UpdateAgeGroupRequest,
  UserProfile,
  TeamListItemDto,
  TeamColorsDto,
  TeamClubDto,
  TeamCoachDto,
  TeamPlayerDto,
  ClubDetailDto,
  ClubColorsDto,
  ClubLocationDto,
  ClubStatisticsDto,
  MatchSummaryDto,
  MatchScoreDto,
  MatchDetailDto,
  MatchLineupDto,
  LineupPlayerDto,
  MatchReportDetailDto,
  GoalDetailDto,
  CardDetailDto,
  InjuryDetailDto,
  PerformanceRatingDto,
  MatchCoachDetailDto,
  MatchSubstitutionDetailDto,
  CreateMatchRequest,
  CreateMatchLineupRequest,
  CreateLineupPlayerRequest,
  CreateMatchReportRequest,
  CreateGoalRequest,
  CreateCardRequest,
  CreateInjuryRequest,
  CreatePerformanceRatingRequest,
  CreateMatchSubstitutionRequest,
  UpdateMatchRequest,
  UpdateMatchLineupRequest,
  UpdateLineupPlayerRequest,
  UpdateMatchReportRequest,
  UpdateGoalRequest,
  UpdateCardRequest,
  UpdateInjuryRequest,
  UpdatePerformanceRatingRequest,
  UpdateMatchSubstitutionRequest,
  AgeGroupListDto,
  AgeGroupDetailDto,
  AgeGroupStatisticsDto,
  AgeGroupPerformerDto,
  AgeGroupCoachDto,
  AgeGroupCoachTeamDto,
  TeamWithStatsDto,
  TeamStatsDto,
  TeamOverviewDto,
  TeamOverviewTeamDto,
  TeamOverviewStatisticsDto,
  TeamMatchSummaryDto,
  TeamPerformerDto,
  TeamTrainingSessionDto,
  ClubPlayerDto,
  ClubPlayerAgeGroupDto,
  ClubPlayerTeamDto,
  ClubTeamDto,
  ClubTeamColorsDto,
  ClubCoachDto,
  ClubCoachTeamDto,
  CoachDetailDto,
  CoachTeamAssignmentDto,
  CoachAgeGroupCoordinatorDto,
  ClubTrainingSessionDto,
  ClubTrainingSessionsDto,
  TrainingSessionDetailDto,
  SessionDrillDetailDto,
  SessionAttendanceDetailDto,
  SessionCoachDetailDto,
  AppliedTemplateDetailDto,
  CreateTrainingSessionRequest,
  CreateSessionDrillRequest,
  CreateSessionAttendanceRequest,
  CreateAppliedTemplateRequest,
  UpdateTrainingSessionRequest,
  UpdateSessionDrillRequest,
  UpdateSessionAttendanceRequest,
  ClubMatchDto,
  ClubMatchesDto,
  ClubKitDto,
  ClubReportCardDto,
  ClubReportCardPlayerDto,
  ClubReportCardPeriodDto,
  ClubReportCardDevelopmentActionDto,
  ClubReportCardSimilarProfessionalDto,
  TacticScopeDto,
  TacticListDto,
  TacticsByScopeResponseDto,
  TacticDetailDto,
  TacticDetailScopeDto,
  PositionOverrideDto,
  TacticPrincipleDto,
  CreateTacticRequest,
  UpdateTacticRequest,
  DrillLinkDto,
  DrillListDto,
  DrillsByScopeResponseDto,
  DrillTemplateListDto,
  DrillTemplatesByScopeResponseDto,
  ClubDevelopmentPlanDto,
  ClubDevelopmentPlanPlayerDto,
  ClubDevelopmentPlanGoalDto,
  ClubDevelopmentPlanPeriodDto,
  AgeGroupDevelopmentPlanSummaryDto,
  AgeGroupDevelopmentPlanPlayerDto,
  AgeGroupDevelopmentPlanGoalSummaryDto,
  AgeGroupDevelopmentPlanPeriodDto,
  DevelopmentPlanDto,
  DevelopmentGoalDto,
  CreateDevelopmentPlanRequest,
  CreateDevelopmentGoalRequest,
  UpdateDevelopmentPlanRequest,
  UpdateDevelopmentGoalRequest,
  PlayerDto,
  PlayerTeamMinimalDto,
  UpdatePlayerRequest,
  UpdateClubRequest,
  CreateTeamRequest,
  UpdateTeamRequest,
} from './client';

// React hooks
export {
  useMyTeams,
  useTeamOverview,
  useTeamPlayers,
  useTeamCoaches,
  useTeamsByAgeGroupId,
  useMyChildren,
  useClubById,
  useClubStatistics,
  useAgeGroupsByClubId,
  useAgeGroupById,
  useAgeGroupStatistics,
  useClubPlayers,
  useClubTeams,
  useClubCoaches,
  useClubTrainingSessions,
  useTrainingSession,
  useCreateTrainingSession,
  useUpdateTrainingSession,
  useClubMatches,
  useClubKits,
  useClubReportCards,
  useClubDevelopmentPlans,
  useAgeGroupDevelopmentPlans,
  useTacticsByScope,
  useTactic,
  useCreateTactic,
  useUpdateTactic,
  useDrillsByScope,
  useDrillTemplatesByScope,
  useCoach,
  usePlayer,
  useDevelopmentPlan,
  useMatch,
  useUpdateAgeGroup,
  useUpdatePlayer,
  useUpdateClub,
  useCreateMatch,
  useUpdateMatch,
  useCreateTeam,
  useUpdateTeam,
} from './hooks';
export type { ApiError, UseMutationState } from './hooks';

// User API
export { getCurrentUser } from './users';
export type { UserProfile as UserProfileType } from './users';
