// <auto-generated> This file has been manually created for shareable club posts support. </auto-generated>
#nullable disable
using System;

namespace OurGame.Persistence.Models;

/// <summary>
/// Shareable content post for a club (match report link, player spotlight, upcoming fixture, result, clip).
/// </summary>
public partial class ClubPost
{
    public Guid Id { get; set; }

    public Guid ClubId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string ImageUrl { get; set; }

    public string ExternalUrl { get; set; }

    public string PostType { get; set; }

    public bool IsPublic { get; set; }

    public Guid? LinkedEntityId { get; set; }

    public string LinkedEntityType { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Club Club { get; set; }
}
