// <auto-generated> This file has been manually created for club social media links support. </auto-generated>
#nullable disable
using System;

namespace OurGame.Persistence.Models;

/// <summary>
/// One row per club storing all social media profile links.
/// </summary>
public partial class ClubSocialLinks
{
    public Guid Id { get; set; }

    public Guid ClubId { get; set; }

    public string Website { get; set; }

    public string Twitter { get; set; }

    public string Instagram { get; set; }

    public string Facebook { get; set; }

    public string YouTube { get; set; }

    public string TikTok { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Club Club { get; set; }
}
