// <auto-generated> This file has been manually created for in-app notifications read tracking. </auto-generated>
#nullable disable
using System;

namespace OurGame.Persistence.Models;

/// <summary>
/// Tracks whether a specific user has viewed a notification.
/// </summary>
public partial class NotificationRead
{
    public Guid Id { get; set; }

    public Guid NotificationId { get; set; }

    public Guid UserId { get; set; }

    public DateTime ReadAt { get; set; }

    public virtual Notification Notification { get; set; }

    public virtual User User { get; set; }
}
