// <auto-generated> This file has been manually created for in-app notifications support. </auto-generated>
#nullable disable
using System;

namespace OurGame.Persistence.Models;

/// <summary>
/// Stored notification that can be global (UserId null) or user-targeted.
/// </summary>
public partial class Notification
{
    public Guid Id { get; set; }

    public Guid? UserId { get; set; }

    public string Type { get; set; }

    public string Title { get; set; }

    public string Message { get; set; }

    public string Url { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual User User { get; set; }
}
