// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace OurGame.Persistence.Models;

public partial class OurGameContext : DbContext
{
    public OurGameContext(DbContextOptions<OurGameContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AgeGroup> AgeGroups { get; set; }

    public virtual DbSet<AgeGroupCoordinator> AgeGroupCoordinators { get; set; }

    public virtual DbSet<AppliedTemplate> AppliedTemplates { get; set; }

    public virtual DbSet<AttributeEvaluation> AttributeEvaluations { get; set; }

    public virtual DbSet<Card> Cards { get; set; }

    public virtual DbSet<Club> Clubs { get; set; }

    public virtual DbSet<Coach> Coaches { get; set; }

    public virtual DbSet<DevelopmentGoal> DevelopmentGoals { get; set; }

    public virtual DbSet<DevelopmentPlan> DevelopmentPlans { get; set; }

    public virtual DbSet<Drill> Drills { get; set; }

    public virtual DbSet<DrillLink> DrillLinks { get; set; }

    public virtual DbSet<DrillTemplate> DrillTemplates { get; set; }

    public virtual DbSet<EmergencyContact> EmergencyContacts { get; set; }

    public virtual DbSet<EvaluationAttribute> EvaluationAttributes { get; set; }

    public virtual DbSet<Formation> Formations { get; set; }

    public virtual DbSet<FormationPosition> FormationPositions { get; set; }

    public virtual DbSet<Goal> Goals { get; set; }

    public virtual DbSet<Injury> Injuries { get; set; }

    public virtual DbSet<Kit> Kits { get; set; }

    public virtual DbSet<KitOrder> KitOrders { get; set; }

    public virtual DbSet<KitOrderItem> KitOrderItems { get; set; }

    public virtual DbSet<LineupPlayer> LineupPlayers { get; set; }

    public virtual DbSet<Match> Matches { get; set; }

    public virtual DbSet<MatchCoach> MatchCoaches { get; set; }

    public virtual DbSet<MatchLineup> MatchLineups { get; set; }

    public virtual DbSet<MatchReport> MatchReports { get; set; }

    public virtual DbSet<MatchSubstitution> MatchSubstitutions { get; set; }

    public virtual DbSet<PerformanceRating> PerformanceRatings { get; set; }

    public virtual DbSet<PersonalSession> PersonalSessions { get; set; }

    public virtual DbSet<PersonalSessionDrill> PersonalSessionDrills { get; set; }

    public virtual DbSet<Player> Players { get; set; }

    public virtual DbSet<PlayerAgeGroup> PlayerAgeGroups { get; set; }

    public virtual DbSet<PlayerAttribute> PlayerAttributes { get; set; }

    public virtual DbSet<PlayerImage> PlayerImages { get; set; }

    public virtual DbSet<PlayerParent> PlayerParents { get; set; }

    public virtual DbSet<PlayerReport> PlayerReports { get; set; }

    public virtual DbSet<PlayerTeam> PlayerTeams { get; set; }

    public virtual DbSet<PositionOverride> PositionOverrides { get; set; }

    public virtual DbSet<ProgressNote> ProgressNotes { get; set; }

    public virtual DbSet<ReportDevelopmentAction> ReportDevelopmentActions { get; set; }

    public virtual DbSet<SessionAttendance> SessionAttendances { get; set; }

    public virtual DbSet<SessionCoach> SessionCoaches { get; set; }

    public virtual DbSet<SessionDrill> SessionDrills { get; set; }

    public virtual DbSet<SimilarProfessional> SimilarProfessionals { get; set; }

    public virtual DbSet<TacticPrinciple> TacticPrinciples { get; set; }

    public virtual DbSet<Team> Teams { get; set; }

    public virtual DbSet<TeamCoach> TeamCoaches { get; set; }

    public virtual DbSet<TemplateDrill> TemplateDrills { get; set; }

    public virtual DbSet<TrainingObjective> TrainingObjectives { get; set; }

    public virtual DbSet<TrainingPlan> TrainingPlans { get; set; }

    public virtual DbSet<TrainingSession> TrainingSessions { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
