// <auto-generated> This file has been manually created for push notification support. </auto-generated>
#nullable disable
using System;

namespace OurGame.Persistence.Models;

/// <summary>
/// Stores a Web Push API subscription for a user so the server can send push notifications.
/// </summary>
public partial class PushSubscription
{
    /// <summary>
    /// Primary key – unique identifier for this subscription record.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// The user who owns this subscription.
    /// </summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// The push service endpoint URL provided by the browser's push service.
    /// </summary>
    public string Endpoint { get; set; }

    /// <summary>
    /// The p256dh key from the browser subscription (base64url-encoded).
    /// </summary>
    public string P256dh { get; set; }

    /// <summary>
    /// The auth secret from the browser subscription (base64url-encoded).
    /// </summary>
    public string Auth { get; set; }

    /// <summary>
    /// When this subscription was created.
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Navigation property to the owning user.
    /// </summary>
    public virtual User User { get; set; }
}
